trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'windows-latest' # Choose an appropriate agent with required tools installed

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x' # Use the appropriate .NET SDK version

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'

  - task: CmdLine@2
    displayName: 'Install Maui Workload'
    inputs:
     script: 'dotnet workload install maui'
  
  - script: dotnet maui build -t:SignAndroidPackage -p:Configuration=Release
    displayName: 'Build Maui App for Android'

  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'drop'
      downloadPath: '$(System.ArtifactsDirectory)/BuildOutput'

  - script: |
      npm install -g firebase-tools
      firebase login:ci --interactive
      firebase appdistribution:distribute '$(System.ArtifactsDirectory)/BuildOutput/app-release.apk'
    displayName: 'Upload to Firebase App Distribution'
