name: CD Build

on:
  workflow_dispatch:
  push:
    branches: [ "develpment" ]
    paths-ignore:
      - "**.md"
      - '**/*.gitignore'
      - '**/*.gitattributes'
      - '**/*.yml'
  pull_request:
    branches: [ "develpment" ]

env:
  BUILD_VERSION: '2.0'
  DOTNET_VERSION: 8.0.x
  XCODE_VERSION: 14.3
  DOTNET_VERSION_TARGETS: net8.0
  CSPROJ_TO_BUILD: 'Deacons.Hybrid.Mobile.csproj'
  PROJECT_FOLDER: 'Deacons_Blazor_Hybrid/Deacons.Hybrid.Mobile'

jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:      
      buildVersion: ${{ env.BUILD_VERSION }}
      dotnetVersion: ${{ env.DOTNET_VERSION }}
      xcodeVersion: ${{ env.XCODE_VERSION }}
      dotnetVersionTargets: ${{ env.DOTNET_VERSION_TARGETS }}
      csprojToBuild: ${{ env.CSPROJ_TO_BUILD }}
      projectFolder: ${{ env.PROJECT_FOLDER }}   
     
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Setup .NET SDK
       uses: actions/setup-dotnet@v1
       with:
        dotnet-version: '8.x'

     - name: Restore NuGet packages
       run: dotnet restore

     - name: Build and publish Maui app
       run: dotnet publish -c Release -r net8.0-android --self-contained false

     - name: Install Firebase CLI
       run: |
        curl -sL https://firebase.tools | bash
        export PATH=$PATH:$HOME/.firebase/bin

     - name: Upload to Firebase App Distribution
       uses: wzieba/Firebase-Distribution-Github-Action@v1
       with:
            appId: '1:741869894335:android:7be6dd14f0a652512c240a'
            groups: wifeandme
            file: ./bin/Release/net8.0-android/com.deacons.admin.app.apk     